-- Sync incremental de enums/campos operacionais em Venda para base legada.

SET @db_name := DATABASE();

SET @sql := IF(
  (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @db_name AND TABLE_NAME = 'Venda' AND COLUMN_NAME = 'status') = 0,
  'ALTER TABLE `Venda` ADD COLUMN `status` ENUM(''AGUARDANDO_PAGAMENTO'',''PAGO'',''SEPARADO'',''FATURADO'',''ENVIADO'',''ENTREGUE'',''CANCELADO'',''ESTORNADO'') NOT NULL DEFAULT ''AGUARDANDO_PAGAMENTO''',
  'SELECT 1'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql := IF(
  (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @db_name AND TABLE_NAME = 'Venda' AND COLUMN_NAME = 'tipo') = 0,
  'ALTER TABLE `Venda` ADD COLUMN `tipo` ENUM(''PDV'',''PEDIDO'',''ORCAMENTO_CONVERTIDO'',''MARKETPLACE'',''ASSINATURA'',''SERVICO'') NOT NULL DEFAULT ''PDV''',
  'SELECT 1'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql := IF(
  (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @db_name AND TABLE_NAME = 'Venda' AND COLUMN_NAME = 'origem') = 0,
  'ALTER TABLE `Venda` ADD COLUMN `origem` ENUM(''PDV'',''BALCAO'',''MERCADO_LIVRE'',''SHOPEE'',''AMAZON'',''MAGAZINE_LUIZA'',''BLING'',''API'',''MANUAL'',''OFFLINE'') NOT NULL DEFAULT ''PDV''',
  'SELECT 1'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql := IF(
  (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @db_name AND TABLE_NAME = 'Venda' AND COLUMN_NAME = 'dataPagamento') = 0,
  'ALTER TABLE `Venda` ADD COLUMN `dataPagamento` DATETIME(3) NULL',
  'SELECT 1'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql := IF(
  (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = @db_name AND TABLE_NAME = 'Venda' AND INDEX_NAME = 'Venda_status_data_idx') = 0,
  'CREATE INDEX `Venda_status_data_idx` ON `Venda`(`status`, `data`)',
  'SELECT 1'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
