import { z } from "zod";

export const produtoSchema = z.object({
    nome: z.string().min(1, "Nome e obrigatorio"),
    marcaId: z.string().min(1, "Marca e obrigatoria"),
    tipo: z.enum(["FISICO", "SERVICO", "DIGITAL", "KIT"]).default("FISICO"),
    sku: z.string().optional(),
    gtin: z.string().optional(),
    referencia: z.string().optional(),
    descricaoCurta: z.string().optional(),
    descricaoLonga: z.string().optional(),
    codigo: z.string().optional(),
    codigoBarras: z.string().optional(),
    cor: z.string().optional(),
    tamanho: z.string().optional(),
    grupoProdutoId: z.string().optional(),
    ncm: z.string().optional(),
    cest: z.string().optional(),
    cfop: z.string().optional(),
    cst: z.string().optional(),
    origemFiscal: z.string().optional(),
    aliquota: z.number().nonnegative().optional(),
    peso: z.number().nonnegative("Peso deve ser positivo").default(0),
    porte: z.string().default("UNICO"),
    altura: z.number().nonnegative().optional(),
    largura: z.number().nonnegative().optional(),
    comprimento: z.number().nonnegative().optional(),
    unidadeMedida: z.string().default("UN"),
    custoMedio: z.number().nonnegative().optional(),
    preco: z.number().nonnegative("Preco deve ser positivo"),
    margem: z.number().optional(),
    markup: z.number().optional(),
    estoque: z.number().int().nonnegative("Estoque nao pode ser negativo").default(0),
    estoqueMinimo: z.number().nonnegative().default(0),
    estoqueMaximo: z.number().nonnegative().optional(),
    estoqueReservado: z.number().nonnegative().default(0),
    localizacao: z.string().optional(),
    mercadoLivreId: z.string().optional(),
    shopeeId: z.string().optional(),
    amazonId: z.string().optional(),
    magazineLuizaId: z.string().optional(),
    blingId: z.string().optional(),
    controlaLote: z.boolean().default(false),
    controlaSerie: z.boolean().default(false),
    ativo: z.boolean().default(true),
}).transform((produto) => ({
    ...produto,
    estoqueDisponivel: produto.estoque - produto.estoqueReservado,
}));

export type ProdutoInput = z.infer<typeof produtoSchema>;
